# .github/workflows/cloudstack-ci.yml

name: CI - CloudStack Homelab

on:
  push:
    paths:
      - 'homelab-virtual-playground/**'
  pull_request:
    paths:
      - 'homelab-virtual-playground/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    name: Ansible Lint and Syntax Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible and lint tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Lint playbook
        run: ansible-lint homelab-virtual-playground/main.yml

      - name: Ansible syntax check
        run: ansible-playbook --syntax-check homelab-virtual-playground/main.yml
